### ISSUE TITLE
ImportError: cannot import name 'rnn_cell'

### ISSUE THREAD

**Issue by alasjesner** [hunkim/word-rnn-tensorflow#53]
Does the import statement change for Windows?
I'm sorry, I'm not pretty versed in Python. 
![error_rnn](https://cloud.githubusercontent.com/assets/13919937/24078152/b41ebaba-0c8b-11e7-95cc-7287c1deedef.PNG)

**Comment by ammarasmro** [comment]
What version of Tensorflow are you running this on? The names in the api have changed, for example you need to change the rnn_cell to tf.contrib.rnn.BasicRNNCell and so on. Check the api for the current version

**Comment by irpap** [comment]
alasjener I had the same issue, but I checked out the master1.0 branch which has some updates for tensorflow 1.0, you can try that (`git fetch --all; git checkout master1.0`)

**Comment by hunkim** [comment]
Could you come up with a PR (perhaps using dynamic RNN)?

**Comment by noi01** [comment]
Was running into the same problem. Be sure to check your Tensorflow version with the version of the word-rnn-tensorflow you want to run. For Tensorflow 1.0.1 - get master 1.0 from https://github.com/hunkim/word-rnn-tensorflow/branches .

**Comment by normanheckscher** [comment]
Should be working with the tensorflow 1.1 release candidate. Works from the head.
